/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-14 16:40:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class base_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Navod%20Madusanka/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1697039427616L));
    _jspx_dependants.put("jar:file:/C:/Users/Navod%20Madusanka/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("  <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${App.getString('app_name')}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" || Home-01</title>\r\n");
      out.write("  <meta name=\"robots\" content=\"noindex, follow\" />\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <!-- Favicon -->\r\n");
      out.write("  <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/images/favicon.png\">\r\n");
      out.write("\r\n");
      out.write("  <!-- CSS\r\n");
      out.write("  ============================================ -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendor/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendor/font-awesome.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendor/flaticon/flaticon.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendor/slick.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendor/slick-theme.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendor/jquery-ui.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendor/sal.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendor/magnific-popup.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/vendor/base.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/style.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"sticky-header newsletter-popup-modal\">\r\n");
      out.write("\r\n");
      out.write("<!--[if lte IE 9]>\r\n");
      out.write("<p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve your experience and security.</p>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<a href=\"#top\" class=\"back-to-top\" id=\"backto-top\"><i class=\"fal fa-arrow-up\"></i></a>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fblock_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Start Footer Area  -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Footer Area  -->\r\n");
      out.write("\r\n");
      out.write("<!-- Product Quick View Modal Start -->\r\n");
      out.write("<div class=\"modal fade quick-view-product\" id=\"quick-view-modal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"><i class=\"far fa-times\"></i></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"single-product-thumb\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-7 mb--40\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-10 order-lg-2\">\r\n");
      out.write("                  <div class=\"single-product-thumbnail product-large-thumbnail axil-product thumbnail-badge zoom-gallery\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/product/product-big-01.png\" alt=\"Product Images\">\r\n");
      out.write("                      <div class=\"label-block label-right\">\r\n");
      out.write("                        <div class=\"product-badget\">20% OFF</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"product-quick-view position-view\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/product/product-big-01.png\" class=\"popup-zoom\">\r\n");
      out.write("                          <i class=\"far fa-search-plus\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/product/product-big-02.png\" alt=\"Product Images\">\r\n");
      out.write("                      <div class=\"label-block label-right\">\r\n");
      out.write("                        <div class=\"product-badget\">20% OFF</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"product-quick-view position-view\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/product/product-big-02.png\" class=\"popup-zoom\">\r\n");
      out.write("                          <i class=\"far fa-search-plus\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/product/product-big-03.png\" alt=\"Product Images\">\r\n");
      out.write("                      <div class=\"label-block label-right\">\r\n");
      out.write("                        <div class=\"product-badget\">20% OFF</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"product-quick-view position-view\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/product/product-big-03.png\" class=\"popup-zoom\">\r\n");
      out.write("                          <i class=\"far fa-search-plus\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-2 order-lg-1\">\r\n");
      out.write("                  <div class=\"product-small-thumb small-thumb-wrapper\">\r\n");
      out.write("                    <div class=\"small-thumb-img\">\r\n");
      out.write("                      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/product/product-thumb/thumb-08.png\" alt=\"thumb image\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"small-thumb-img\">\r\n");
      out.write("                      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/product/product-thumb/thumb-07.png\" alt=\"thumb image\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"small-thumb-img\">\r\n");
      out.write("                      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/product/product-thumb/thumb-09.png\" alt=\"thumb image\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-5 mb--40\">\r\n");
      out.write("              <div class=\"single-product-content\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                  <div class=\"product-rating\">\r\n");
      out.write("                    <div class=\"star-rating\">\r\n");
      out.write("                      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/icons/rate.png\" alt=\"Rate Images\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"review-link\">\r\n");
      out.write("                      <a href=\"#\">(<span>1</span> customer reviews)</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h3 class=\"product-title\">Serif Coffee Table</h3>\r\n");
      out.write("                  <span class=\"price-amount\">$155.00 - $255.00</span>\r\n");
      out.write("                  <ul class=\"product-meta\">\r\n");
      out.write("                    <li><i class=\"fal fa-check\"></i>In stock</li>\r\n");
      out.write("                    <li><i class=\"fal fa-check\"></i>Free delivery available</li>\r\n");
      out.write("                    <li><i class=\"fal fa-check\"></i>Sales 30% Off Use Code: MOTIVE30</li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <p class=\"description\">In ornare lorem ut est dapibus, ut tincidunt nisi pretium. Integer ante est, elementum eget magna. Pellentesque sagittis dictum libero, eu dignissim tellus.</p>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"product-variations-wrapper\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Start Product Variation  -->\r\n");
      out.write("                    <div class=\"product-variation\">\r\n");
      out.write("                      <h6 class=\"title\">Colors:</h6>\r\n");
      out.write("                      <div class=\"color-variant-wrapper\">\r\n");
      out.write("                        <ul class=\"color-variant mt--0\">\r\n");
      out.write("                          <li class=\"color-extra-01 active\"><span><span class=\"color\"></span></span>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li class=\"color-extra-02\"><span><span class=\"color\"></span></span>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li class=\"color-extra-03\"><span><span class=\"color\"></span></span>\r\n");
      out.write("                          </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End Product Variation  -->\r\n");
      out.write("\r\n");
      out.write("                    <!-- Start Product Variation  -->\r\n");
      out.write("                    <div class=\"product-variation\">\r\n");
      out.write("                      <h6 class=\"title\">Size:</h6>\r\n");
      out.write("                      <ul class=\"range-variant\">\r\n");
      out.write("                        <li>xs</li>\r\n");
      out.write("                        <li>s</li>\r\n");
      out.write("                        <li>m</li>\r\n");
      out.write("                        <li>l</li>\r\n");
      out.write("                        <li>xl</li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End Product Variation  -->\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <!-- Start Product Action Wrapper  -->\r\n");
      out.write("                  <div class=\"product-action-wrapper d-flex-center\">\r\n");
      out.write("                    <!-- Start Quentity Action  -->\r\n");
      out.write("                    <div class=\"pro-qty\"><input type=\"text\" value=\"1\"></div>\r\n");
      out.write("                    <!-- End Quentity Action  -->\r\n");
      out.write("\r\n");
      out.write("                    <!-- Start Product Action  -->\r\n");
      out.write("                    <ul class=\"product-action d-flex-center mb--0\">\r\n");
      out.write("                      <li class=\"add-to-cart\"><a href=\"cart.html\" class=\"axil-btn btn-bg-primary\">Add to Cart</a></li>\r\n");
      out.write("                      <li class=\"wishlist\"><a href=\"wishlist.html\" class=\"axil-btn wishlist-btn\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- End Product Action  -->\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- End Product Action Wrapper  -->\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Product Quick View Modal End -->\r\n");
      out.write("\r\n");
      out.write("<!-- Header Search Modal End -->\r\n");
      out.write("<div class=\"header-search-modal\" id=\"header-search-modal\">\r\n");
      out.write("  <button class=\"card-close sidebar-close\"><i class=\"fas fa-times\"></i></button>\r\n");
      out.write("  <div class=\"header-search-wrap\">\r\n");
      out.write("    <div class=\"card-header\">\r\n");
      out.write("      <form action=\"#\">\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("          <input type=\"search\" class=\"form-control\" name=\"prod-search\" id=\"prod-search\" placeholder=\"Write Something....\">\r\n");
      out.write("          <button type=\"submit\" class=\"axil-btn btn-bg-primary\"><i class=\"far fa-search\"></i></button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-body\">\r\n");
      out.write("      <div class=\"search-result-header\">\r\n");
      out.write("        <h6 class=\"title\">24 Result Found</h6>\r\n");
      out.write("        <a href=\"shop.html\" class=\"view-all\">View All</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"psearch-results\">\r\n");
      out.write("        <div class=\"axil-product-list\">\r\n");
      out.write("          <div class=\"thumbnail\">\r\n");
      out.write("            <a href=\"single-product.html\">\r\n");
      out.write("              <img src=\"./assets/images/product/electric/product-09.png\" alt=\"Yantiti Leather Bags\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"product-content\">\r\n");
      out.write("            <div class=\"product-rating\">\r\n");
      out.write("                                <span class=\"rating-icon\">\r\n");
      out.write("                                <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                <i class=\"fal fa-star\"></i>\r\n");
      out.write("                            </span>\r\n");
      out.write("              <span class=\"rating-number\"><span>100+</span> Reviews</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h6 class=\"product-title\"><a href=\"single-product.html\">Media Remote</a></h6>\r\n");
      out.write("            <div class=\"product-price-variant\">\r\n");
      out.write("              <span class=\"price current-price\">$29.99</span>\r\n");
      out.write("              <span class=\"price old-price\">$49.99</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"product-cart\">\r\n");
      out.write("              <a href=\"cart.html\" class=\"cart-btn\"><i class=\"fal fa-shopping-cart\"></i></a>\r\n");
      out.write("              <a href=\"wishlist.html\" class=\"cart-btn\"><i class=\"fal fa-heart\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"axil-product-list\">\r\n");
      out.write("          <div class=\"thumbnail\">\r\n");
      out.write("            <a href=\"single-product.html\">\r\n");
      out.write("              <img src=\"./assets/images/product/electric/product-09.png\" alt=\"Yantiti Leather Bags\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"product-content\">\r\n");
      out.write("            <div class=\"product-rating\">\r\n");
      out.write("                                <span class=\"rating-icon\">\r\n");
      out.write("                                <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                <i class=\"fal fa-star\"></i>\r\n");
      out.write("                            </span>\r\n");
      out.write("              <span class=\"rating-number\"><span>100+</span> Reviews</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h6 class=\"product-title\"><a href=\"single-product.html\">Media Remote</a></h6>\r\n");
      out.write("            <div class=\"product-price-variant\">\r\n");
      out.write("              <span class=\"price current-price\">$29.99</span>\r\n");
      out.write("              <span class=\"price old-price\">$49.99</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"product-cart\">\r\n");
      out.write("              <a href=\"cart.html\" class=\"cart-btn\"><i class=\"fal fa-shopping-cart\"></i></a>\r\n");
      out.write("              <a href=\"wishlist.html\" class=\"cart-btn\"><i class=\"fal fa-heart\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Header Search Modal End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"cart-dropdown\" id=\"cart-dropdown\">\r\n");
      out.write("  <div class=\"cart-content-wrap\">\r\n");
      out.write("    <div class=\"cart-header\">\r\n");
      out.write("      <h2 class=\"header-title\">Cart review</h2>\r\n");
      out.write("      <button class=\"cart-close sidebar-close\"><i class=\"fas fa-times\"></i></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"cart-body\">\r\n");
      out.write("      <ul class=\"cart-item-list\">\r\n");
      out.write("        <li class=\"cart-item\">\r\n");
      out.write("          <div class=\"item-img\">\r\n");
      out.write("            <a href=\"single-product.html\"><img src=\"assets/images/product/electric/product-01.png\" alt=\"Commodo Blown Lamp\"></a>\r\n");
      out.write("            <button class=\"close-btn\"><i class=\"fas fa-times\"></i></button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item-content\">\r\n");
      out.write("            <div class=\"product-rating\">\r\n");
      out.write("                                <span class=\"icon\">\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("              <span class=\"rating-number\">(64)</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"item-title\"><a href=\"single-product-3.html\">Wireless PS Handler</a></h3>\r\n");
      out.write("            <div class=\"item-price\"><span class=\"currency-symbol\">$</span>155.00</div>\r\n");
      out.write("            <div class=\"pro-qty item-quantity\">\r\n");
      out.write("              <input type=\"number\" class=\"quantity-input\" value=\"15\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"cart-item\">\r\n");
      out.write("          <div class=\"item-img\">\r\n");
      out.write("            <a href=\"single-product-2.html\"><img src=\"assets/images/product/electric/product-02.png\" alt=\"Commodo Blown Lamp\"></a>\r\n");
      out.write("            <button class=\"close-btn\"><i class=\"fas fa-times\"></i></button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item-content\">\r\n");
      out.write("            <div class=\"product-rating\">\r\n");
      out.write("                                <span class=\"icon\">\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("              <span class=\"rating-number\">(4)</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"item-title\"><a href=\"single-product-2.html\">Gradient Light Keyboard</a></h3>\r\n");
      out.write("            <div class=\"item-price\"><span class=\"currency-symbol\">$</span>255.00</div>\r\n");
      out.write("            <div class=\"pro-qty item-quantity\">\r\n");
      out.write("              <input type=\"number\" class=\"quantity-input\" value=\"5\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"cart-item\">\r\n");
      out.write("          <div class=\"item-img\">\r\n");
      out.write("            <a href=\"single-product-3.html\"><img src=\"assets/images/product/electric/product-03.png\" alt=\"Commodo Blown Lamp\"></a>\r\n");
      out.write("            <button class=\"close-btn\"><i class=\"fas fa-times\"></i></button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item-content\">\r\n");
      out.write("            <div class=\"product-rating\">\r\n");
      out.write("                                <span class=\"icon\">\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("								<i class=\"fas fa-star\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("              <span class=\"rating-number\">(6)</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"item-title\"><a href=\"single-product.html\">HD CC Camera</a></h3>\r\n");
      out.write("            <div class=\"item-price\"><span class=\"currency-symbol\">$</span>200.00</div>\r\n");
      out.write("            <div class=\"pro-qty item-quantity\">\r\n");
      out.write("              <input type=\"number\" class=\"quantity-input\" value=\"100\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"cart-footer\">\r\n");
      out.write("      <h3 class=\"cart-subtotal\">\r\n");
      out.write("        <span class=\"subtotal-title\">Subtotal:</span>\r\n");
      out.write("        <span class=\"subtotal-amount\">$610.00</span>\r\n");
      out.write("      </h3>\r\n");
      out.write("      <div class=\"group-btn\">\r\n");
      out.write("        <a href=\"cart.html\" class=\"axil-btn btn-bg-primary viewcart-btn\">View Cart</a>\r\n");
      out.write("        <a href=\"checkout.html\" class=\"axil-btn btn-bg-secondary checkout-btn\">Checkout</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Offer Modal Start -->\r\n");
      out.write("<div class=\"offer-popup-modal\" id=\"offer-popup-modal\">\r\n");
      out.write("  <div class=\"offer-popup-wrap\">\r\n");
      out.write("    <div class=\"card-body\">\r\n");
      out.write("      <button class=\"popup-close\"><i class=\"fas fa-times\"></i></button>\r\n");
      out.write("      <div class=\"content\">\r\n");
      out.write("        <div class=\"section-title-wrapper\">\r\n");
      out.write("          <span class=\"title-highlighter highlighter-primary\"> <i class=\"far fa-shopping-basket\"></i> Donât Miss!!</span>\r\n");
      out.write("          <h3 class=\"title\">Best Sales Offer<br> Grab Yours</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"poster-countdown countdown\"></div>\r\n");
      out.write("        <a href=\"shop.html\" class=\"axil-btn btn-bg-primary\">Shop Now <i class=\"fal fa-long-arrow-right\"></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"closeMask\"></div>\r\n");
      out.write("<!-- Offer Modal End -->\r\n");
      out.write("<!-- JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("<!-- Modernizer JS -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/modernizr.min.js\"></script>\r\n");
      out.write("<!-- jQuery JS -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/jquery.js\"></script>\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/popper.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/slick.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/js.cookie.js\"></script>\r\n");
      out.write("<!-- <script src=\"assets/js/vendor/jquery.style.switcher.js\"></script> -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/jquery-ui.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/jquery.ui.touch-punch.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/jquery.countdown.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/sal.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/isotope.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/counterup.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendor/waypoints.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Main JS -->\r\n");
      out.write("<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("<script src=\"assets/js/secureFetch.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  function secureFetch(url, options = {}) {\r\n");
      out.write("    const token = localStorage.getItem(\"accessToken\");\r\n");
      out.write("    const expireIn = localStorage.getItem(\"expireIn\");\r\n");
      out.write("\r\n");
      out.write("    const expireAt = new Date(Number(expireIn)).getTime();\r\n");
      out.write("    const expireGate = new Date().getTime() + 2 * 60 * 1000;\r\n");
      out.write("\r\n");
      out.write("    if (token && expireAt && expireAt < expireGate) {\r\n");
      out.write("      return refreshToken().then(newToken => {\r\n");
      out.write("        options.headers = {\r\n");
      out.write("          ...options.headers,\r\n");
      out.write("          Authorization: 'Bearer ' + newToken\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        return fetch(url, options);\r\n");
      out.write("      })\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (token) {\r\n");
      out.write("      options.headers = {\r\n");
      out.write("        ...options.headers,\r\n");
      out.write("        Authorization: 'Bearer ' + token\r\n");
      out.write("      }\r\n");
      out.write("    } else {\r\n");
      out.write("      console.log(\"Token Unavailable\");\r\n");
      out.write("      window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("login\"\r\n");
      out.write("    }\r\n");
      out.write("    return fetch(url, options);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function refreshToken() {\r\n");
      out.write("    const oldRefreshToken = localStorage.getItem(\"refreshToken\");\r\n");
      out.write("\r\n");
      out.write("    const fromData = new URLSearchParams();\r\n");
      out.write("    fromData.append('token', oldRefreshToken);\r\n");
      out.write("\r\n");
      out.write("    if (oldRefreshToken) {\r\n");
      out.write("      return fetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("login/refresh-token\", {\r\n");
      out.write("        method: 'post',\r\n");
      out.write("        headers: {\r\n");
      out.write("          'Content-Type': 'application/x-www-form-urlencoded'\r\n");
      out.write("        },\r\n");
      out.write("        body: fromData\r\n");
      out.write("      }).then(response => {\r\n");
      out.write("        if (!response.ok) {\r\n");
      out.write("          window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("login\"\r\n");
      out.write("        }\r\n");
      out.write("        return response.json();\r\n");
      out.write("      }).then(data => {\r\n");
      out.write("        localStorage.setItem(\"accessToken\", data.accessToken);\r\n");
      out.write("        localStorage.setItem(\"refreshToken\", data.refreshToken);\r\n");
      out.write("        localStorage.setItem(\"expireIn\", data.expireIn);\r\n");
      out.write("        return data.accessToken;\r\n");
      out.write("      });\r\n");
      out.write("    } else {\r\n");
      out.write("      localStorage.removeItem(\"accessToken\");\r\n");
      out.write("      localStorage.removeItem(\"expireIn\");\r\n");
      out.write("      window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("login\"\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fblock_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  layout:block
    lk.callidora.jsp.inheritance.BlockTag _jspx_th_layout_005fblock_005f0 = new lk.callidora.jsp.inheritance.BlockTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fblock_005f0);
    try {
      _jspx_th_layout_005fblock_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout/base.jsp(49,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fblock_005f0.setName("content");
      _jspx_th_layout_005fblock_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fblock_005f0);
    }
    return false;
  }
}
