/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-15 08:51:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class base_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Navod%20Madusanka/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1697039427616L));
    _jspx_dependants.put("jar:file:/C:/Users/Navod%20Madusanka/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>eTrade || Sign Up</title>\r\n");
      out.write("    <meta name=\"robots\" content=\"noindex, follow\" />\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/images/favicon.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/vendor/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/vendor/font-awesome.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/vendor/flaticon/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/vendor/slick.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/vendor/slick-theme.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/vendor/jquery-ui.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/vendor/sal.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/vendor/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/vendor/base.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fblock_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("<!-- Modernizer JS -->\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fblock_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script src=\"assets/js/vendor/modernizr.min.js\"></script>\r\n");
      out.write("<!-- jQuery JS -->\r\n");
      out.write("<script src=\"assets/js/vendor/jquery.js\"></script>\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"assets/js/vendor/popper.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/vendor/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/vendor/slick.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/vendor/js.cookie.js\"></script>\r\n");
      out.write("<!-- <script src=\"assets/js/vendor/jquery.style.switcher.js\"></script> -->\r\n");
      out.write("<script src=\"assets/js/vendor/jquery-ui.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/vendor/jquery.ui.touch-punch.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/vendor/jquery.countdown.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/vendor/sal.js\"></script>\r\n");
      out.write("<script src=\"assets/js/vendor/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/vendor/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/vendor/isotope.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/vendor/counterup.js\"></script>\r\n");
      out.write("<script src=\"assets/js/vendor/waypoints.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Main JS -->\r\n");
      out.write("<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fblock_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  layout:block
    lk.callidora.jsp.inheritance.BlockTag _jspx_th_layout_005fblock_005f0 = new lk.callidora.jsp.inheritance.BlockTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fblock_005f0);
    try {
      _jspx_th_layout_005fblock_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout/base_1.jsp(42,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fblock_005f0.setName("signup");
      _jspx_th_layout_005fblock_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fblock_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  layout:block
    lk.callidora.jsp.inheritance.BlockTag _jspx_th_layout_005fblock_005f1 = new lk.callidora.jsp.inheritance.BlockTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fblock_005f1);
    try {
      _jspx_th_layout_005fblock_005f1.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout/base_1.jsp(47,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fblock_005f1.setName("script");
      _jspx_th_layout_005fblock_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fblock_005f1);
    }
    return false;
  }
}
