/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-08-20 02:53:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"service-area\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row row-cols-xl-4 row-cols-sm-2 row-cols-1 row--20\">\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"service-box service-style-2\">\r\n");
      out.write("          <div class=\"icon\">\r\n");
      out.write("            <img src=\"./assets/images/icons/service1.png\" alt=\"Service\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"content\">\r\n");
      out.write("            <h6 class=\"title\">Fast &amp; Secure Delivery</h6>\r\n");
      out.write("            <p>Tell about your service.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"service-box service-style-2\">\r\n");
      out.write("          <div class=\"icon\">\r\n");
      out.write("            <img src=\"./assets/images/icons/service2.png\" alt=\"Service\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"content\">\r\n");
      out.write("            <h6 class=\"title\">Money Back Guarantee</h6>\r\n");
      out.write("            <p>Within 10 days.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"service-box service-style-2\">\r\n");
      out.write("          <div class=\"icon\">\r\n");
      out.write("            <img src=\"./assets/images/icons/service3.png\" alt=\"Service\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"content\">\r\n");
      out.write("            <h6 class=\"title\">24 Hour Return Policy</h6>\r\n");
      out.write("            <p>No question ask.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"service-box service-style-2\">\r\n");
      out.write("          <div class=\"icon\">\r\n");
      out.write("            <img src=\"./assets/images/icons/service4.png\" alt=\"Service\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"content\">\r\n");
      out.write("            <h6 class=\"title\">Pro Quality Support</h6>\r\n");
      out.write("            <p>24/7 Live support.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<footer class=\"axil-footer-area footer-style-2\">\r\n");
      out.write("  <!-- Start Footer Top Area  -->\r\n");
      out.write("  <div class=\"footer-top separator-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <!-- Start Single Widget  -->\r\n");
      out.write("        <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("          <div class=\"axil-footer-widget\">\r\n");
      out.write("            <h5 class=\"widget-title\">Support</h5>\r\n");
      out.write("            <!-- <div class=\"logo mb--30\">\r\n");
      out.write("            <a href=\"index.html\">\r\n");
      out.write("                <img class=\"light-logo\" src=\"assets/images/logo/logo.png\" alt=\"Logo Images\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div> -->\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("              <p>685 Market Street, <br>\r\n");
      out.write("                Las Vegas, LA 95820, <br>\r\n");
      out.write("                United States.\r\n");
      out.write("              </p>\r\n");
      out.write("              <ul class=\"support-list-item\">\r\n");
      out.write("                <li><a href=\"mailto:example@domain.com\"><i class=\"fal fa-envelope-open\"></i> example@domain.com</a></li>\r\n");
      out.write("                <li><a href=\"tel:(+01)850-315-5862\"><i class=\"fal fa-phone-alt\"></i> (+01) 850-315-5862</a></li>\r\n");
      out.write("                <!-- <li><i class=\"fal fa-map-marker-alt\"></i> 685 Market Street,  <br> Las Vegas, LA 95820, <br> United States.</li> -->\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Single Widget  -->\r\n");
      out.write("        <!-- Start Single Widget  -->\r\n");
      out.write("        <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("          <div class=\"axil-footer-widget\">\r\n");
      out.write("            <h5 class=\"widget-title\">Account</h5>\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"my-account.html\">My Account</a></li>\r\n");
      out.write("                <li><a href=\"sign-up.html\">Login / Register</a></li>\r\n");
      out.write("                <li><a href=\"cart.html\">Cart</a></li>\r\n");
      out.write("                <li><a href=\"wishlist.html\">Wishlist</a></li>\r\n");
      out.write("                <li><a href=\"shop.html\">Shop</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Single Widget  -->\r\n");
      out.write("        <!-- Start Single Widget  -->\r\n");
      out.write("        <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("          <div class=\"axil-footer-widget\">\r\n");
      out.write("            <h5 class=\"widget-title\">Quick Link</h5>\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"privacy-policy.html\">Privacy Policy</a></li>\r\n");
      out.write("                <li><a href=\"terms-of-service.html\">Terms Of Use</a></li>\r\n");
      out.write("                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("                <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Single Widget  -->\r\n");
      out.write("        <!-- Start Single Widget  -->\r\n");
      out.write("        <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("          <div class=\"axil-footer-widget\">\r\n");
      out.write("            <h5 class=\"widget-title\">Download App</h5>\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("              <span>Save $3 With App & New User only</span>\r\n");
      out.write("              <div class=\"download-btn-group\">\r\n");
      out.write("                <div class=\"qr-code\">\r\n");
      out.write("                  <img src=\"assets/images/others/qr.png\" alt=\"Axilthemes\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"app-link\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <img src=\"assets/images/others/app-store.png\" alt=\"App Store\">\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <img src=\"assets/images/others/play-store.png\" alt=\"Play Store\">\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Single Widget  -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
