/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-15 11:36:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header class=\"header axil-header header-style-1\">\r\n");
      out.write("    <div class=\"axil-header-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"header-top-dropdown\">\r\n");
      out.write("                        <div class=\"dropdown\">\r\n");
      out.write("                            <button class=\"dropdown-toggle\" type=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                                English\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#\">English</a></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#\">Arabic</a></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#\">Spanish</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"dropdown\">\r\n");
      out.write("                            <button class=\"dropdown-toggle\" type=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                                USD\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#\">USD</a></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#\">AUD</a></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#\">EUR</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"header-top-link\">\r\n");
      out.write("                        <ul class=\"quick-link\">\r\n");
      out.write("                            <li><a href=\"#\">Help</a></li>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("                            <li><a href=\"sign-up.html\">Join Us</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("login\">Sign In</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Start Mainmenu Area  -->\r\n");
      out.write("    <div id=\"axil-sticky-placeholder\"></div>\r\n");
      out.write("    <div class=\"axil-mainmenu\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"header-navbar\">\r\n");
      out.write("                <div class=\"header-brand\">\r\n");
      out.write("                    <a href=\"index.html\" class=\"logo logo-dark\">\r\n");
      out.write("                        <img src=\"assets/images/logo/logo.png\" alt=\"Site Logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"index.html\" class=\"logo logo-light\">\r\n");
      out.write("                        <img src=\"assets/images/logo/logo-light.png\" alt=\"Site Logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"header-main-nav\">\r\n");
      out.write("                    <!-- Start Mainmanu Nav -->\r\n");
      out.write("                    <nav class=\"mainmenu-nav\">\r\n");
      out.write("                        <button class=\"mobile-close-btn mobile-nav-toggler\"><i class=\"fas fa-times\"></i></button>\r\n");
      out.write("                        <div class=\"mobile-nav-brand\">\r\n");
      out.write("                            <a href=\"index.html\" class=\"logo\">\r\n");
      out.write("                                <img src=\"assets/images/logo/logo.png\" alt=\"Site Logo\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul class=\"mainmenu\">\r\n");
      out.write("                            <li class=\"menu-item-has-children\">\r\n");
      out.write("                                <a href=\"#\">Home</a>\r\n");
      out.write("                                <ul class=\"axil-submenu\">\r\n");
      out.write("                                    <li><a href=\"index-1.html\">Home - Electronics</a></li>\r\n");
      out.write("                                    <li><a href=\"index-2.html\">Home - NFT</a></li>\r\n");
      out.write("                                    <li><a href=\"index-3.html\">Home - Fashion</a></li>\r\n");
      out.write("                                    <li><a href=\"index-4.html\">Home - Jewellery</a></li>\r\n");
      out.write("                                    <li><a href=\"index-5.html\">Home - Furniture</a></li>\r\n");
      out.write("                                    <li><a href=\"index-7.html\">Home - Multipurpose</a></li>\r\n");
      out.write("                                    <li><a href=\"https://new.axilthemes.com/demo/template/etrade-rtl/\">RTL Version</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"menu-item-has-children\">\r\n");
      out.write("                                <a href=\"#\">Shop</a>\r\n");
      out.write("                                <ul class=\"axil-submenu\">\r\n");
      out.write("                                    <li><a href=\"shop-sidebar.html\">Shop With Sidebar</a></li>\r\n");
      out.write("                                    <li><a href=\"shop.html\">Shop no Sidebar</a></li>\r\n");
      out.write("                                    <li><a href=\"single-product.html\">Product Variation 1</a></li>\r\n");
      out.write("                                    <li><a href=\"single-product-2.html\">Product Variation 2</a></li>\r\n");
      out.write("                                    <li><a href=\"single-product-3.html\">Product Variation 3</a></li>\r\n");
      out.write("                                    <li><a href=\"single-product-4.html\">Product Variation 4</a></li>\r\n");
      out.write("                                    <li><a href=\"single-product-5.html\">Product Variation 5</a></li>\r\n");
      out.write("                                    <li><a href=\"single-product-6.html\">Product Variation 6</a></li>\r\n");
      out.write("                                    <li><a href=\"single-product-7.html\">Product Variation 7</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"menu-item-has-children\">\r\n");
      out.write("                                <a href=\"#\">Pages</a>\r\n");
      out.write("                                <ul class=\"axil-submenu\">\r\n");
      out.write("                                    <li><a href=\"wishlist.html\">Wishlist</a></li>\r\n");
      out.write("                                    <li><a href=\"cart.html\">Cart</a></li>\r\n");
      out.write("                                    <li><a href=\"checkout.html\">Checkout</a></li>\r\n");
      out.write("                                    <li><a href=\"my-account.html\">Account</a></li>\r\n");
      out.write("                                    <li><a href=\"sign-up.html\">Sign Up</a></li>\r\n");
      out.write("                                    <li><a href=\"sign-in.html\">Sign In</a></li>\r\n");
      out.write("                                    <li><a href=\"forgot-password.html\">Forgot Password</a></li>\r\n");
      out.write("                                    <li><a href=\"reset-password.html\">Reset Password</a></li>\r\n");
      out.write("                                    <li><a href=\"privacy-policy.html\">Privacy Policy</a></li>\r\n");
      out.write("                                    <li><a href=\"coming-soon.html\">Coming Soon</a></li>\r\n");
      out.write("                                    <li><a href=\"404.html\">404 Error</a></li>\r\n");
      out.write("                                    <li><a href=\"typography.html\">Typography</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"about-us.html\">About</a></li>\r\n");
      out.write("                            <li class=\"menu-item-has-children\">\r\n");
      out.write("                                <a href=\"#\">Blog</a>\r\n");
      out.write("                                <ul class=\"axil-submenu\">\r\n");
      out.write("                                    <li><a href=\"blog.html\">Blog List</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-grid.html\">Blog Grid</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-details.html\">Standard Post</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-gallery.html\">Gallery Post</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-video.html\">Video Post</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-audio.html\">Audio Post</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-quote.html\">Quote Post</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <!-- End Mainmanu Nav -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"header-action\">\r\n");
      out.write("                    <ul class=\"action-list\">\r\n");
      out.write("                        <li class=\"axil-search\">\r\n");
      out.write("                            <a href=\"javascript:void(0)\" class=\"header-search-icon\" title=\"Search\">\r\n");
      out.write("                                <i class=\"flaticon-magnifying-glass\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"wishlist\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <i class=\"flaticon-heart\" onclick=\"gotoWishList();\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"shopping-cart\">\r\n");
      out.write("                            <a href=\"#\" class=\"cart-dropdown-btn\">\r\n");
      out.write("                                <span class=\"cart-count\">3</span>\r\n");
      out.write("                                <i class=\"flaticon-shopping-cart\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"my-account\">\r\n");
      out.write("                            <a href=\"javascript:void(0)\">\r\n");
      out.write("                                <i class=\"flaticon-person\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"my-account-dropdown\">\r\n");
      out.write("                                <span class=\"title\">QUICKLINKS</span>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"my-account.html\">My Account</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">Initiate return</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">Support</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">Language</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                                <div class=\"login-btn\">\r\n");
      out.write("                                    <a href=\"sign-in.html\" class=\"axil-btn btn-bg-primary\">Login</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"reg-footer text-center\">No account yet? <a href=\"sign-up.html\" class=\"btn-link\">REGISTER HERE.</a></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"axil-mobile-toggle\">\r\n");
      out.write("                            <button class=\"menu-btn mobile-nav-toggler\">\r\n");
      out.write("                                <i class=\"flaticon-menu-2\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Mainmenu Area -->\r\n");
      out.write("</header>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
