/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-13 04:33:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.backend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Navod%20Madusanka/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1697039427616L));
    _jspx_dependants.put("jar:file:/C:/Users/Navod%20Madusanka/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/backend/dashboard.jsp(2,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("admin_base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/backend/dashboard.jsp(3,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <div class=\"dashboard-ecommerce\">\r\n");
      out.write("            <div class=\"container-fluid dashboard-content \">\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- pageheader  -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("                        <div class=\"page-header\">\r\n");
      out.write("                            <h2 class=\"pageheader-title\">E-commerce Dashboard Template </h2>\r\n");
      out.write("                            <p class=\"pageheader-text\">Nulla euismod urna eros, sit amet scelerisque torton lectus vel mauris facilisis faucibus at enim quis massa lobortis rutrum.</p>\r\n");
      out.write("                            <div class=\"page-breadcrumb\">\r\n");
      out.write("                                <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                                    <ol class=\"breadcrumb\">\r\n");
      out.write("                                        <li class=\"breadcrumb-item\"><a href=\"#\" class=\"breadcrumb-link\">Dashboard</a></li>\r\n");
      out.write("                                        <li class=\"breadcrumb-item active\" aria-current=\"page\">E-Commerce Dashboard Template</li>\r\n");
      out.write("                                    </ol>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- end pageheader  -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"ecommerce-widget\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"text-muted\">Total Revenue</h5>\r\n");
      out.write("                                    <div class=\"metric-value d-inline-block\">\r\n");
      out.write("                                        <h1 class=\"mb-1\">$12099</h1>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"metric-label d-inline-block float-right text-success font-weight-bold\">\r\n");
      out.write("                                        <span><i class=\"fa fa-fw fa-arrow-up\"></i></span><span>5.86%</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"sparkline-revenue\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"text-muted\">Affiliate Revenue</h5>\r\n");
      out.write("                                    <div class=\"metric-value d-inline-block\">\r\n");
      out.write("                                        <h1 class=\"mb-1\">$12099</h1>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"metric-label d-inline-block float-right text-success font-weight-bold\">\r\n");
      out.write("                                        <span><i class=\"fa fa-fw fa-arrow-up\"></i></span><span>5.86%</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"sparkline-revenue2\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"text-muted\">Refunds</h5>\r\n");
      out.write("                                    <div class=\"metric-value d-inline-block\">\r\n");
      out.write("                                        <h1 class=\"mb-1\">0.00</h1>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"metric-label d-inline-block float-right text-primary font-weight-bold\">\r\n");
      out.write("                                        <span>N/A</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"sparkline-revenue3\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"text-muted\">Avg. Revenue Per User</h5>\r\n");
      out.write("                                    <div class=\"metric-value d-inline-block\">\r\n");
      out.write("                                        <h1 class=\"mb-1\">$28000</h1>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"metric-label d-inline-block float-right text-secondary font-weight-bold\">\r\n");
      out.write("                                        <span>-2.00%</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"sparkline-revenue4\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("\r\n");
      out.write("                        <!-- recent orders  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <div class=\"col-xl-9 col-lg-12 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <h5 class=\"card-header\">Recent Orders</h5>\r\n");
      out.write("                                <div class=\"card-body p-0\">\r\n");
      out.write("                                    <div class=\"table-responsive\">\r\n");
      out.write("                                        <table class=\"table\">\r\n");
      out.write("                                            <thead class=\"bg-light\">\r\n");
      out.write("                                            <tr class=\"border-0\">\r\n");
      out.write("                                                <th class=\"border-0\">#</th>\r\n");
      out.write("                                                <th class=\"border-0\">Image</th>\r\n");
      out.write("                                                <th class=\"border-0\">Product Name</th>\r\n");
      out.write("                                                <th class=\"border-0\">Product Id</th>\r\n");
      out.write("                                                <th class=\"border-0\">Quantity</th>\r\n");
      out.write("                                                <th class=\"border-0\">Price</th>\r\n");
      out.write("                                                <th class=\"border-0\">Order Time</th>\r\n");
      out.write("                                                <th class=\"border-0\">Customer</th>\r\n");
      out.write("                                                <th class=\"border-0\">Status</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            </thead>\r\n");
      out.write("                                            <tbody>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>1</td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <div class=\"m-r-10\"><img src=\"assets/images/product-pic.jpg\" alt=\"user\" class=\"rounded\" width=\"45\"></div>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>Product #1 </td>\r\n");
      out.write("                                                <td>id000001 </td>\r\n");
      out.write("                                                <td>20</td>\r\n");
      out.write("                                                <td>$80.00</td>\r\n");
      out.write("                                                <td>27-08-2018 01:22:12</td>\r\n");
      out.write("                                                <td>Patricia J. King </td>\r\n");
      out.write("                                                <td><span class=\"badge-dot badge-brand mr-1\"></span>InTransit </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>2</td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <div class=\"m-r-10\"><img src=\"assets/images/product-pic-2.jpg\" alt=\"user\" class=\"rounded\" width=\"45\"></div>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>Product #2 </td>\r\n");
      out.write("                                                <td>id000002 </td>\r\n");
      out.write("                                                <td>12</td>\r\n");
      out.write("                                                <td>$180.00</td>\r\n");
      out.write("                                                <td>25-08-2018 21:12:56</td>\r\n");
      out.write("                                                <td>Rachel J. Wicker </td>\r\n");
      out.write("                                                <td><span class=\"badge-dot badge-success mr-1\"></span>Delivered </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>3</td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <div class=\"m-r-10\"><img src=\"assets/images/product-pic-3.jpg\" alt=\"user\" class=\"rounded\" width=\"45\"></div>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>Product #3 </td>\r\n");
      out.write("                                                <td>id000003 </td>\r\n");
      out.write("                                                <td>23</td>\r\n");
      out.write("                                                <td>$820.00</td>\r\n");
      out.write("                                                <td>24-08-2018 14:12:77</td>\r\n");
      out.write("                                                <td>Michael K. Ledford </td>\r\n");
      out.write("                                                <td><span class=\"badge-dot badge-success mr-1\"></span>Delivered </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>4</td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <div class=\"m-r-10\"><img src=\"assets/images/product-pic-4.jpg\" alt=\"user\" class=\"rounded\" width=\"45\"></div>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>Product #4 </td>\r\n");
      out.write("                                                <td>id000004 </td>\r\n");
      out.write("                                                <td>34</td>\r\n");
      out.write("                                                <td>$340.00</td>\r\n");
      out.write("                                                <td>23-08-2018 09:12:35</td>\r\n");
      out.write("                                                <td>Michael K. Ledford </td>\r\n");
      out.write("                                                <td><span class=\"badge-dot badge-success mr-1\"></span>Delivered </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td colspan=\"9\"><a href=\"#\" class=\"btn btn-outline-light float-right\">View Details</a></td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            </tbody>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- end recent orders  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- customer acquistion  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <h5 class=\"card-header\">Customer Acquisition</h5>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"ct-chart ct-golden-section\" style=\"height: 354px;\"></div>\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                            <span class=\"legend-item mr-2\">\r\n");
      out.write("                                                    <span class=\"fa-xs text-primary mr-1 legend-tile\"><i class=\"fa fa-fw fa-square-full\"></i></span>\r\n");
      out.write("                                            <span class=\"legend-text\">Returning</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        <span class=\"legend-item mr-2\">\r\n");
      out.write("\r\n");
      out.write("                                                    <span class=\"fa-xs text-secondary mr-1 legend-tile\"><i class=\"fa fa-fw fa-square-full\"></i></span>\r\n");
      out.write("                                            <span class=\"legend-text\">First Time</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- end customer acquistion  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- product category  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <h5 class=\"card-header\"> Product Category</h5>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"ct-chart-category ct-golden-section\" style=\"height: 315px;\"></div>\r\n");
      out.write("                                    <div class=\"text-center m-t-40\">\r\n");
      out.write("                                            <span class=\"legend-item mr-3\">\r\n");
      out.write("                                                    <span class=\"fa-xs text-primary mr-1 legend-tile\"><i class=\"fa fa-fw fa-square-full \"></i></span><span class=\"legend-text\">Man</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        <span class=\"legend-item mr-3\">\r\n");
      out.write("                                                <span class=\"fa-xs text-secondary mr-1 legend-tile\"><i class=\"fa fa-fw fa-square-full\"></i></span>\r\n");
      out.write("                                            <span class=\"legend-text\">Woman</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        <span class=\"legend-item mr-3\">\r\n");
      out.write("                                                <span class=\"fa-xs text-info mr-1 legend-tile\"><i class=\"fa fa-fw fa-square-full\"></i></span>\r\n");
      out.write("                                            <span class=\"legend-text\">Accessories</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- end product category  -->\r\n");
      out.write("                        <!-- product sales  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <div class=\"col-xl-6 col-lg-12 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-header\">\r\n");
      out.write("                                    <!-- <div class=\"float-right\">\r\n");
      out.write("                                            <select class=\"custom-select\">\r\n");
      out.write("                                                <option selected>Today</option>\r\n");
      out.write("                                                <option value=\"1\">Weekly</option>\r\n");
      out.write("                                                <option value=\"2\">Monthly</option>\r\n");
      out.write("                                                <option value=\"3\">Yearly</option>\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                        </div> -->\r\n");
      out.write("                                    <h5 class=\"mb-0\"> Product Sales</h5>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"ct-chart-product ct-golden-section\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- end product sales  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-12 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <!-- ============================================================== -->\r\n");
      out.write("                            <!-- top perfomimg  -->\r\n");
      out.write("                            <!-- ============================================================== -->\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <h5 class=\"card-header\">Top Performing Campaigns</h5>\r\n");
      out.write("                                <div class=\"card-body p-0\">\r\n");
      out.write("                                    <div class=\"table-responsive\">\r\n");
      out.write("                                        <table class=\"table no-wrap p-table\">\r\n");
      out.write("                                            <thead class=\"bg-light\">\r\n");
      out.write("                                            <tr class=\"border-0\">\r\n");
      out.write("                                                <th class=\"border-0\">Campaign</th>\r\n");
      out.write("                                                <th class=\"border-0\">Visits</th>\r\n");
      out.write("                                                <th class=\"border-0\">Revenue</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            </thead>\r\n");
      out.write("                                            <tbody>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>Campaign#1</td>\r\n");
      out.write("                                                <td>98,789 </td>\r\n");
      out.write("                                                <td>$4563</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>Campaign#2</td>\r\n");
      out.write("                                                <td>2,789 </td>\r\n");
      out.write("                                                <td>$325</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>Campaign#3</td>\r\n");
      out.write("                                                <td>1,459 </td>\r\n");
      out.write("                                                <td>$225</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>Campaign#4</td>\r\n");
      out.write("                                                <td>5,035 </td>\r\n");
      out.write("                                                <td>$856</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>Campaign#5</td>\r\n");
      out.write("                                                <td>10,000 </td>\r\n");
      out.write("                                                <td>$1000</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>Campaign#5</td>\r\n");
      out.write("                                                <td>10,000 </td>\r\n");
      out.write("                                                <td>$1000</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td colspan=\"3\">\r\n");
      out.write("                                                    <a href=\"#\" class=\"btn btn-outline-light float-right\">Details</a>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            </tbody>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- ============================================================== -->\r\n");
      out.write("                            <!-- end top perfomimg  -->\r\n");
      out.write("                            <!-- ============================================================== -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- sales  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card border-3 border-top border-top-primary\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"text-muted\">Sales</h5>\r\n");
      out.write("                                    <div class=\"metric-value d-inline-block\">\r\n");
      out.write("                                        <h1 class=\"mb-1\">$12099</h1>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"metric-label d-inline-block float-right text-success font-weight-bold\">\r\n");
      out.write("                                        <span class=\"icon-circle-small icon-box-xs text-success bg-success-light\"><i class=\"fa fa-fw fa-arrow-up\"></i></span><span class=\"ml-1\">5.86%</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- end sales  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- new customer  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card border-3 border-top border-top-primary\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"text-muted\">New Customer</h5>\r\n");
      out.write("                                    <div class=\"metric-value d-inline-block\">\r\n");
      out.write("                                        <h1 class=\"mb-1\">1245</h1>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"metric-label d-inline-block float-right text-success font-weight-bold\">\r\n");
      out.write("                                        <span class=\"icon-circle-small icon-box-xs text-success bg-success-light\"><i class=\"fa fa-fw fa-arrow-up\"></i></span><span class=\"ml-1\">10%</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- end new customer  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- visitor  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card border-3 border-top border-top-primary\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"text-muted\">Visitor</h5>\r\n");
      out.write("                                    <div class=\"metric-value d-inline-block\">\r\n");
      out.write("                                        <h1 class=\"mb-1\">13000</h1>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"metric-label d-inline-block float-right text-success font-weight-bold\">\r\n");
      out.write("                                        <span class=\"icon-circle-small icon-box-xs text-success bg-success-light\"><i class=\"fa fa-fw fa-arrow-up\"></i></span><span class=\"ml-1\">5%</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- end visitor  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- total orders  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card border-3 border-top border-top-primary\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"text-muted\">Total Orders</h5>\r\n");
      out.write("                                    <div class=\"metric-value d-inline-block\">\r\n");
      out.write("                                        <h1 class=\"mb-1\">1340</h1>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"metric-label d-inline-block float-right text-danger font-weight-bold\">\r\n");
      out.write("                                        <span class=\"icon-circle-small icon-box-xs text-danger bg-danger-light bg-danger-light \"><i class=\"fa fa-fw fa-arrow-down\"></i></span><span class=\"ml-1\">4%</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- end total orders  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- total revenue  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- category revenue  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <div class=\"col-xl-5 col-lg-5 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <h5 class=\"card-header\">Revenue by Category</h5>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div id=\"c3chart_category\" style=\"height: 420px;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- end category revenue  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-xl-7 col-lg-7 col-md-12 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <h5 class=\"card-header\"> Total Revenue</h5>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div id=\"morris_totalrevenue\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-footer\">\r\n");
      out.write("                                    <p class=\"display-7 font-weight-bold\"><span class=\"text-primary d-inline-block\">$26,000</span><span class=\"text-success float-right\">+9.45%</span></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-5 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <!-- ============================================================== -->\r\n");
      out.write("                            <!-- social source  -->\r\n");
      out.write("                            <!-- ============================================================== -->\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <h5 class=\"card-header\"> Sales By Social Source</h5>\r\n");
      out.write("                                <div class=\"card-body p-0\">\r\n");
      out.write("                                    <ul class=\"social-sales list-group list-group-flush\">\r\n");
      out.write("                                        <li class=\"list-group-item social-sales-content\"><span class=\"social-sales-icon-circle facebook-bgcolor mr-2\"><i class=\"fab fa-facebook-f\"></i></span><span class=\"social-sales-name\">Facebook</span><span class=\"social-sales-count text-dark\">120 Sales</span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-group-item social-sales-content\"><span class=\"social-sales-icon-circle twitter-bgcolor mr-2\"><i class=\"fab fa-twitter\"></i></span><span class=\"social-sales-name\">Twitter</span><span class=\"social-sales-count text-dark\">99 Sales</span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-group-item social-sales-content\"><span class=\"social-sales-icon-circle instagram-bgcolor mr-2\"><i class=\"fab fa-instagram\"></i></span><span class=\"social-sales-name\">Instagram</span><span class=\"social-sales-count text-dark\">76 Sales</span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-group-item social-sales-content\"><span class=\"social-sales-icon-circle pinterest-bgcolor mr-2\"><i class=\"fab fa-pinterest-p\"></i></span><span class=\"social-sales-name\">Pinterest</span><span class=\"social-sales-count text-dark\">56 Sales</span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-group-item social-sales-content\"><span class=\"social-sales-icon-circle googleplus-bgcolor mr-2\"><i class=\"fab fa-google-plus-g\"></i></span><span class=\"social-sales-name\">Google Plus</span><span class=\"social-sales-count text-dark\">36 Sales</span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-footer text-center\">\r\n");
      out.write("                                    <a href=\"#\" class=\"btn-primary-link\">View Details</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- ============================================================== -->\r\n");
      out.write("                            <!-- end social source  -->\r\n");
      out.write("                            <!-- ============================================================== -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <!-- ============================================================== -->\r\n");
      out.write("                            <!-- sales traffice source  -->\r\n");
      out.write("                            <!-- ============================================================== -->\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <h5 class=\"card-header\"> Sales By Traffic Source</h5>\r\n");
      out.write("                                <div class=\"card-body p-0\">\r\n");
      out.write("                                    <ul class=\"traffic-sales list-group list-group-flush\">\r\n");
      out.write("                                        <li class=\"traffic-sales-content list-group-item \"><span class=\"traffic-sales-name\">Direct</span><span class=\"traffic-sales-amount\">$4000.00  <span class=\"icon-circle-small icon-box-xs text-success ml-4 bg-success-light\"><i class=\"fa fa-fw fa-arrow-up\"></i></span><span class=\"ml-1 text-success\">5.86%</span></span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"traffic-sales-content list-group-item\"><span class=\"traffic-sales-name\">Search<span class=\"traffic-sales-amount\">$3123.00  <span class=\"icon-circle-small icon-box-xs text-success ml-4 bg-success-light\"><i class=\"fa fa-fw fa-arrow-up\"></i></span><span class=\"ml-1 text-success\">5.86%</span></span>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"traffic-sales-content list-group-item\"><span class=\"traffic-sales-name\">Social<span class=\"traffic-sales-amount \">$3099.00  <span class=\"icon-circle-small icon-box-xs text-success ml-4 bg-success-light\"><i class=\"fa fa-fw fa-arrow-up\"></i></span><span class=\"ml-1 text-success\">5.86%</span></span>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"traffic-sales-content list-group-item\"><span class=\"traffic-sales-name\">Referrals<span class=\"traffic-sales-amount \">$2220.00   <span class=\"icon-circle-small icon-box-xs text-danger ml-4 bg-danger-light\"><i class=\"fa fa-fw fa-arrow-down\"></i></span><span class=\"ml-1 text-danger\">4.02%</span></span>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"traffic-sales-content list-group-item \"><span class=\"traffic-sales-name\">Email<span class=\"traffic-sales-amount\">$1567.00   <span class=\"icon-circle-small icon-box-xs text-danger ml-4 bg-danger-light\"><i class=\"fa fa-fw fa-arrow-down\"></i></span><span class=\"ml-1 text-danger\">3.86%</span></span>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-footer text-center\">\r\n");
      out.write("                                    <a href=\"#\" class=\"btn-primary-link\">View Details</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- end sales traffice source  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- sales traffic country source  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-12 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <h5 class=\"card-header\">Sales By Country Traffic Source</h5>\r\n");
      out.write("                                <div class=\"card-body p-0\">\r\n");
      out.write("                                    <ul class=\"country-sales list-group list-group-flush\">\r\n");
      out.write("                                        <li class=\"country-sales-content list-group-item\"><span class=\"mr-2\"><i class=\"flag-icon flag-icon-us\" title=\"us\" id=\"us\"></i> </span>\r\n");
      out.write("                                            <span class=\"\">United States</span><span class=\"float-right text-dark\">78%</span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-group-item country-sales-content\"><span class=\"mr-2\"><i class=\"flag-icon flag-icon-ca\" title=\"ca\" id=\"ca\"></i></span><span class=\"\">Canada</span><span class=\"float-right text-dark\">7%</span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-group-item country-sales-content\"><span class=\"mr-2\"><i class=\"flag-icon flag-icon-ru\" title=\"ru\" id=\"ru\"></i></span><span class=\"\">Russia</span><span class=\"float-right text-dark\">4%</span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-group-item country-sales-content\"><span class=\" mr-2\"><i class=\"flag-icon flag-icon-in\" title=\"in\" id=\"in\"></i></span><span class=\"\">India</span><span class=\"float-right text-dark\">12%</span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-group-item country-sales-content\"><span class=\" mr-2\"><i class=\"flag-icon flag-icon-fr\" title=\"fr\" id=\"fr\"></i></span><span class=\"\">France</span><span class=\"float-right text-dark\">16%</span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-footer text-center\">\r\n");
      out.write("                                    <a href=\"#\" class=\"btn-primary-link\">View Details</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- end sales traffice country source  -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
